In [1]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
import re
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\xuxue\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [2]:
p = set(stopwords.words('english'))

In [3]:
ignore = list(p)

In [5]:
pwd

'C:\\Users\\xuxue'

# Tokenizing Sentences

In [7]:
df = pd.read_json('clean-data.json',encoding='gb18030')

In [8]:
final_df = df.reset_index()

In [9]:
final_df = final_df.drop('index',axis=1)

In [10]:
x = final_df['text']

In [11]:
cleaned_text = [w.lower() for w in x]

In [12]:
def word_extraction(sentence):
    p = set(stopwords.words('english'))
    ignore = list(p)
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text

In [13]:
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

In [14]:
p= tokenize(cleaned_text)

In [15]:
print("Word List for Document \n{0} \n".format(p))

Word List for Document 
['0', '000', '01', '04', '06', '07', '1', '10', '100', '1000', '101', '1060', '109', '10k', '11', '110', '111', '113', '117', '11th', '12', '120', '128', '13', '130', '132', '135', '136', '139', '14', '140', '15', '150', '153', '15th', '16', '163', '17', '170', '172', '173', '175', '18', '180', '181', '186', '18th', '19', '190', '191', '1933', '1934', '1mdb', '1p', '1q', '2', '20', '200', '2002', '2003', '2005', '2007', '2009', '2010', '2011', '2012', '2014', '2015', '2016', '2017', '2018', '2019', '202', '2020', '2020s', '2021', '2022', '2023', '2025', '205', '2060', '2070', '2080', '20s', '21', '215', '2170', '22', '222', '227', '229', '23', '230', '238', '24', '25', '250', '256', '25th', '26', '268', '269', '27', '270', '274', '28', '280', '28th', '29', '293', '29th', '3', '30', '300', '31', '312', '31st', '32', '329', '33', '34', '340', '348', '349', '35', '350', '36', '360', '365', '37', '377', '378', '38', '39', '399', '3d', '3p', '3q', '3s', '4', '40', '4

In [16]:
for sentence in cleaned_text:
    words = word_extraction(sentence)
    p= tokenize(cleaned_text)
    bag_vector = np.zeros(len(p))
    for w in words:
        for i,word in enumerate(p):
            if word == w: 
                bag_vector[i] += 1
    print("{0}\n{1}\n".format(sentence,np.array(bag_vector)))

thank you, ellen. we have a strong 2018, with total revenues of $136.8 billion, up 23% over 2017, reflecting the benefit of our ongoing investments to deliver exceptional experiences for users and compelling returns for our advertisers, partners and enterprise customers.
[0. 0. 0. ... 0. 0. 0.]

stock-based compensation totaled $2.3 billion. headcount at the end of the quarter was 98,771, up 4,399 from last quarter. consistent with prior quarters, the majority of new hires were engineers and product managers. in terms of product areas, the most sizable head count increases were in cloud for both technical and sales roles.
[0. 0. 0. ... 0. 0. 0.]

for the full-year 2018, other bets revenues were $595 million, up 25% versus 2017 primarily generated by fiber and verily. operating loss for other bets was $3.4 billion for the full-year 2018 versus an operating loss of $2.7 billion in 2017. other bets accrued capex was $181 million, down from $493 million in 2017 primarily reflecting investm

sure, and i appreciate the question. obviously, we think about this, and we monitor it carefully. first, i'll talk about employees first, and i think morale and the firm for employees is high. employees feel good about the performance of the firm. they do not like the fact that we're dealing with the situation in 1mdb. and certainly, i think people here are extremely angry and upset about the fact that we had a partner of the firm involved in such a significant fraud. and as i said in my remarks, that's something that we have enormous regret about. but the business has performed well. i think people recognize that this is something that we're going through a deliberative process of resolving. but people feel good about the firm, our client franchise, the work they're doing with our clients and the way the firm's positioned. in terms of our clients, we obviously are extremely engaged with our clients and are talking to our clients on a regular basis, and i would say the impact on our cl

brennan hawken
[0. 0. 0. ... 0. 0. 0.]

curious on marcus deposits. we've heard here in the last few days a few banks commenting on the likelihood that we could see retail deposit costs increasing even if we don't see any short-term rate increases. if that plays out in 2019, could you maybe let us know how you would think about keeping your position competitively in the market at the upper end of that bound as far as payout goes, how you would adjust? just how should we think about that as far the market deposits go?
[0. 0. 0. ... 0. 0. 0.]

we think it was a, q4 in particular was a great quarter for customers that retail, there is a lot of strength in the retail part of the businesses, the teams here had done a great job, planning, preparing and then executing on the quarter. aws maintained a very strong growth rate and continued to deliver for customers. we had a great reinvent conference in the quarter. so we feel good about the growth in the quarter and also the total revenue and i

stephen scherr
[0. 0. 0. ... 0. 0. 0.]

[technical difficulty] example of that is in any lending business, when you are in a growth mode, you continue to have reserve build right to the point at which you are at a comfortable, steady state. and from there, you start to see the margin increase. and so i think that each of these businesses, whether it's corporate cash management or marcus, are all in their early stages. they haven't yet hit their stride, notwithstanding our expectation that they'll hit the targets we set for them in 2020. those targets were, by no means, a limit of where we think we can take the firm in terms of the overall growth trajectory generally. i would also say that the commentary on efficiency and higher marginal margin should not be limited exclusively to kind of the growth initiatives themselves. so look at ficc, for example. ficc over time, and david was talking about this, there's an element of platform electronification as a means of which you can drive hig

and then on capital, especially infrastructure capital, if you use the capital lease slide as maybe an indicator for what we have invested into our aws business to support infrastructure and global expansion, that number grew 10% last year, when it had grown 69% in 2017. so in a lot of ways, 2018 was about banking the efficiencies of investments in people, warehouses, infrastructure that we had put in place in 2016 and 17. so while we'll continue to concurrently drive growth and customer offering and prime benefits, we certainly do take costs seriously and we will continue to work on operational efficiencies. i would expect these investments to increase relative to 2018 and we've reflected what we see so far in q1 in our guidance.
[0. 0. 0. ... 0. 0. 0.]

sure. so what we have seen from mifid ii is really market share consolidation, and it's played out at one level by geography and then another level in terms of individual firms. so we've seen more share consolidate, and that consolida

next, on cash management. as we evaluated opportunities to improve services to our clients and expand our franchise, cash management presents an illogical area for us given the breadth of our corporate relationships and the size of that wallet. in addition, the pace of technological change in the payment space gives us confidence that it is appropriate time for us to address this opportunity. we are now 6 months into a 2-year build, and our firm will be first to use a cash management platform later in 2019. in addition to validating the product, doing our own operational payment flows will reduce costs and operational risk. among all -- assuming all progresses as planned, we expect to launch the product to clients in 2020.
[0. 0. 0. ... 0. 0. 0.]

lastly, as we bring markets and the business of investment management closer, we will continue to evolve markets from a single product to a multiproduct platform. we now serve 3 million customers through our lending and savings products in cl

with that, let's switch gears and review our performance as highlighted on page 4. for 2018 full year, the firm reported solid results. we generated firm-wide net revenues of $36.6 billion, our highest in 8 years. we delivered a return on equity of 13.3% and return on tangible equity of 14.1%. importantly, we are making significant investments to further expand our client franchise, grow revenues and enhance the long-term earnings profile of the firm, the cost of which is being funded by the embedded operating leverage in our businesses.
[0. 0. 0. ... 0. 0. 0.]

in summary, i'm extremely pleased with our performance. we delivered a solid year, and our 2018 results leave us on strong footing to pursue our strategic objectives in 2019 and beyond. the team i have assembled to execute on our priorities, including john and stephen, have an increased sense of urgency and discipline to help move our business forward.
[0. 0. 0. ... 0. 0. 0.]

with that, i'll turn the call over to stephen, who 

conference call participants
[0. 0. 0. ... 0. 0. 0.]

thanks for taking my questions. i have two. just -- the first one is to go back to the fourth quarter gross margins. i think if we try to back out aws, it looks like there was a little more gross margin pressure. can you just talk to any of the puts and takes we should know about from a gross margin perspective in the fourth quarter and then that other line that i think includes the advertising business, can you just help us, any help at all on the growth of the advertising business or the impact of any of the accounting changes in the quarter? thanks.
[0. 0. 0. ... 0. 0. 0.]

first, we successfully increased our wallet share by 65 basis points since 2016 with our institutional client base per coalition. however, this provided a minimal top line benefit so far given the market backdrop. nevertheless, we continue to broaden our client and product footprint and deepen our relationships to drive higher rankings and market share.
[0. 0.

moving on to taxes. as mentioned earlier, our tax rate for 2018 was 16%. based on our current interpretations of the rules and legislative guidance to date, we expect our 2019 tax rate to be between 22% and 23%, excluding the impact of equity-based compensation.
[0. 0. 0. ... 0. 0. 0.]

turning to page 13 on capital. our common equity tier 1 ratio was 13.3% using the standardized approach and 13.1% under the advanced approach, up 20 basis points and 70 basis points, respectively, versus the third quarter. the improvement in the advanced ratio reflected 80 basis points related to lower credit risk weighted assets due to inclusion of the firm's default experience into the determination of probability of default calculation. our supplementing leverage ratio finished at 6.2%.
[0. 0. 0. ... 0. 0. 0.]

for the full year, we repurchased 13.9 million shares of common stock worth $3.3 billion, contributing to a reduction in our basic share count of 8 million shares for the year, reaching a reco

chinedu bolu - sanford c. bernstein & co.
[0. 0. 0. ... 0. 0. 0.]

operator
[0. 0. 0. ... 0. 0. 0.]

your next question is from the line of michael carrier with bank of america merrill lynch.
[0. 0. 0. ... 0. 0. 0.]

michael carrier
[0. 0. 0. ... 0. 0. 0.]

stephen, maybe one more, just on the i&l business. it's obviously one that's tough to predict. but when i think about some of the sales that you mentioned and how that drove the benefit in the quarter, can you give us any kind of color or indication of maybe what the value is in the portfolio versus, like, the cost base? just to get some sense on maybe what the potential, like, realizations as you have these sales over the next year or 2 could potentially be?
[0. 0. 0. ... 0. 0. 0.]

stephen scherr
[0. 0. 0. ... 0. 0. 0.]

sure. thanks for the question. i think it's difficult for me to give you a sense of the delta in the [technical difficulty] relative to where we carry it. i would ask you to sort of rely more on the progression an

pairing dlss with ray tracing can provide comparable frame rates to traditional restorization but also much more beautiful cinematic visual, the best of both worlds. this is the next generation of gaming. while this was a challenging quarter in our gaming business we look forward to putting the channel inventory correction behind us and building on the solid foundation of our turing architecture.
[0. 0. 0. ... 0. 0. 0.]

moving to data center. revenue was $679 million, up 12% year-on-year and down 14% sequentially. full year data center revenue was $2.93 billion, up a strong 52%. the q4 sales decline was broad based across verticals and markets and geographies. as the quarter progressed, customers around the world became increasingly cautious due to rising economic uncertainty and the number of deals did not close in january.
[0. 0. 0. ... 0. 0. 0.]

in addition, hyperscale and cloud purchases declined both sequentially and year-on-year as several customers paused at the end of the yea

for fiscal 2020, we expect q1 to mark the bottom as we passed the inventory correction in gaming. we expect total revenue for the year to be flat to down slightly with growth in our four end markets, compensating for the absence of crypto revenue and the excess selling for most year. we plan to grow opex in the high single digits this year, and we continue to invest in our focus growth areas of graphics, ai and self-driving cars. further financial details are included in the cfo commentary, and other information is available on our ir web site.
[0. 0. 0. ... 0. 0. 0.]

in closing, i'd like to highlight upcoming events for the financial community; we will be presenting at the morgan stanley technology, media and telecom conference on february 26; and our next earnings call to discuss our financial results for the quarter of fiscal 2020 take place on may 15th.
[0. 0. 0. ... 0. 0. 0.]

i had two questions. first, colette, you talked about the weakness you saw in the 2070 and the 2080 in t

on gross margin, our gross margin, the largest contributor to our absolute gross margin is really just the mix of our product. the mix of our products based on our market platforms, but also the mix of our products within data center, as well as within gaming. we provided guidance for q1, which has a good level of confidence from us and we'll see how it goes from there.
[0. 0. 0. ... 0. 0. 0.]

the fundamentals of gaming has not changed, there more gamers than ever. games are better than ever. there's been a recent shift in the popularity of multiplayer competitive e-sports like games, that's good for hardware. it lowers the barrier to entry, because it's free to play with the exception of downloadable content. and so the barriers to entry is lower but you could see that the excitement around fortnight and recently with apex legend, pubg is still popular, league of legends is still popular. and so this genre of games is both competitive, requires great hardware, it attracts a lot more 

the second way is data analytics. this is a brand new thing for us. you must know that big data and using data to predict dynamics in the marketplaces is really important in retail and e-tail, and healthcare, and financial services. and there's never been accelerated approach to solve this problem for people. and because of the flexibility of cuda and because the performance of architecture, over the course of last year, we reengineered the entire data analytics stack. so that we can accelerate, it's called rapids. that work is really, really important and i hope to give you guys updates on that on a regular basis. rendering is a brand new market for us, because of turing, finally we can we can render photo realistic images in accelerated way. there are millions of servers in the world that are driving render farms and they're getting upgraded on a regular basis.
[0. 0. 0. ... 0. 0. 0.]

and then lastly, we've been successful with csps, because they're easy for us to reach. but the wor

well, in the short-term, in the near-term, we have relatively limited visibility. we don't think it's going to remain this way. and with a little bit of tailwind, i think we could have a fairly good year. and so we'll just see how it turns out. this is our year guidance for now and we'll update you as we go. the fundamental dynamics doesn't change. the fact of the matter is that world needs more computing. and a lot of that computing is related to machine learning, data analytics, deep learning. it's related to the things that we're working on. and we have four new ways to grow our data center business. i think our deep learning position is as good as ever. our scientific computing position is as good as ever. and we have four new ways to grow; we have inference, we have data analytics and machine learning, we have rendering and now we're taking that entire stack to the enterprise. and so i think we have the right strategy, we have the best platform and the utilization, the utility of 

and to also answer your question regarding dram prices, yes, they have definitely been volatile over the historical period. it is great to see them coming down in price. over the long-term, yes, that is beneficial to us from a gross margin perspective. so as we look out to the quarters or later, we will probably be able to incorporate that into our gross margin.
[0. 0. 0. ... 0. 0. 0.]

crypto mining demand and its after effects have distorted the quarter-to-quarter trends in the gaming business and obscured its underlying trend line. let me try to give you some visibility into what we believe the long live business looks like. as you know, our gaming business consists of desktop gaming, notebook gaming and gaming console products. to get a sense of the underlying run rate in our gaming business last year, it is helpful to look at desktop gaming revenue across the period that doesn't include crypto demand.
[0. 0. 0. ... 0. 0. 0.]

and your next question comes from the line of aaron rak

and so those applications most of the developers today use machine learning and large big data analytics. so we invested in the stack called rapids and built our architecture, called t4. and we're in the process of partnering with large it companies to take the stack and the solution out to the world's enterprise. and so, i expect enterprise to be a fairly exciting growth opportunity for us. meanwhile, the csps, their pause will end. the amount of computation they do is increasing. more and more of them are using deep learning. and we have inference opportunity with the work that we do with t4 and tensorrt. and so we've got a lot of exciting opportunities to go.
[0. 0. 0. ... 0. 0. 0.]

and your next question comes from the line of pierre ferragu with new street research.
[0. 0. 0. ... 0. 0. 0.]

a question for colette, i'm trying to figure out how your position with cloud data centers evolved last year in financial year 2019. so if i look at the cloud capex, we are up about 70%. if i 

got you. can i ask one more at the tail end here?
[0. 0. 0. ... 0. 0. 0.]

i think, we're 鈥
[0. 0. 0. ... 0. 0. 0.]

can i ask just sort of quick one? just for greg. greg, when we think about the 727 engine versus the max, just for modeling purposes it's going to review 90% maxs this year. how do we think about the margin profile of one variant versus the other?
[0. 0. 0. ... 0. 0. 0.]

 thanks for taking the question. maybe two if i can. one on the media side, has there been any step-up in terms of investments around media content to support your ambition with respect to prime and the video. it's been a couple of years now since we got an update on rate of spend or how it might impact either historical periods or going forward periods, that would be number one.and then number two, going back to lloyd's question on the advertising front, how do you think about the video opportunity, you're moving beyond just branded opportunities or sponsored products search on your own properties and 

if i just wanted to make sure that i understood what your -- that point you're making on china, dennis, do you potentially see a low in orders this year because the next five year plan is looming in the headlights. and then totally unrelated question and apologies for that, but where does cfm stand on its catch-up plan for the leap? how unusual is it for boeing to embed your people in their supply chain?
[0. 0. 0. ... 0. 0. 0.]

ulie, on your first question regarding china that was exactly my point earlier, given the five-year planning cycle there, we are having ongoing discussions with our customers in china, the chinese government, the u.s. government. this also factors into the trade dialogue between the u.s. and china. but these are all factors that we鈥檙e very much engaged in. again, we expect china as a long-term growth market for us. but exactly how those efforts play out over the next quarter or two is still an open question as we proceed with trade discussions. i can tell you h

in summary, we delivered another year of strong operating performance, captured noteworthy additions to our large and diverse backlog, returned significant cash to our shareholders, invested in our people and in our business to drive innovation and excellence and complemented our organic growth with planned strategic inorganic investments. with that, let鈥檚 turn to the business environment on slide 3.
[0. 0. 0. ... 0. 0. 0.]

we continue to see healthy global demand for our offerings in commercial, defense, space and services. these are sizable sectors that are growing and backed by strong fundamentals with a combined market opportunity of $8.1 trillion over the next 10 years. i would note that as a global company with customers in 150 countries, we're always mindful of the potential impact of geopolitical and macroeconomic forces. we continue to track a host of near-term issues and mitigate potential risks as appropriate. we value and maintain strong relationships with our customers, s

in summary, with growing markets and opportunities ahead, our team remained intensely focused on growth, innovation and accelerating productivity improvements to fuel our investments in the future. for example, the first test flight of our autonomous passenger air vehicle prototype last week chose our efforts to continue to lead with the safe, innovative and responsible approach to new mobility solutions. our one boeing strategies and offerings across our three businesses are key differentiators that helps demand our position as the world's leading aerospace company.
[0. 0. 0. ... 0. 0. 0.]

with that, greg, over to you for the financial results.
[0. 0. 0. ... 0. 0. 0.]

 thanks. just two, so just can you comment, did advertising slow down relative to third quarter. one, you kind of adjusting for 606 and then secondly, was there any reallocation in segments between online and physical stores and if not any commentary why physical stores was down year-over-year? thanks.
[0. 0. 0. ... 0.

total company revenue for 2019 is forecasted to be between $109.5 and $111.5 billion, largely reflecting higher plan 737 and 787 production rate and growth in both services as well as defense, space, and security. core earnings per share guidance for 2019 is set to be between $19.90 and $20.10 per share on higher volume, favorable mix and improved productivity and affordability.
[0. 0. 0. ... 0. 0. 0.]

operating cash flow for 2019 is forecasted to increase by $2 billion to be between $17 billion and $17.5 billion. this is largely driven by improved 787 cash generation in 2019, higher overall volume, including 737 and 787 production and improving tanker cash profile that partially offset by increased plan 777x inventory related test aircraft and early build units and higher cash taxes, primarily due to improved unit profitability, as well as higher planned r&d spending in 2019.
[0. 0. 0. ... 0. 0. 0.]

capital spending is forecasted to be approximately $2.3 billion and includes the tim

with that, i'll turn it back to dennis for some closing comments.
[0. 0. 0. ... 0. 0. 0.]

all right. thanks greg. 2018 was the year of strong performance and record results on many different fronts operationally and financially. a demonstration of how our team remains focused on further driving both growth and productivity. these results were achieved through the hard work and dedication of our employees and the great partnerships that we have with our customers and suppliers. in addition to the strong commercial airplane market dynamics i mentioned earlier in my remarks, we have taken our own actions to reduce cyclicality in our business. this includes remaining disciplined in our production rate decisions, derisking our pension liabilities, strategically phasing our research and development spending, creating labor stability with long-term contracts, and expanding our services business, which is also less cyclical.
[0. 0. 0. ... 0. 0. 0.]

good afternoon, everyone. brian, can we jus

if you look at the stats on traffic growth, cargo, global expansion of route structures all the fundamentals remained very strong, and we鈥檙e encouraged by that. so we expect to see continuing steady orders volume. i wouldn't expect that to change significantly depending on the nma decision. so we鈥檙e going to be in the marketplace continuing to compete and win. i guess one other reminder on nma, if we do decide to proceed with the authority to offer -- don't expect a big change in the r&d profile. this is all part of our planned r&d profile. as greg said earlier, we expect r&d to continue to be roughly the same in terms of percentage of revenue going forward. so as revenue grows, you will see some r&d growth. that will be at the same percent. and if we launch nma, it will better end on the backside of 777x. so from a profile standpoint it fits very nicely. greg anything, do you want to add on that?
[0. 0. 0. ... 0. 0. 0.]

and then on your question of marketing, yes, the marketing perce

does that help year-on-year.
[0. 0. 0. ... 0. 0. 0.]

yes. so obviously, we will manage that extremely tight as we always do, but we got budgets in place there and clear initiatives in business cases to go drive that. they're at a little over and above what we we're spending in 2018.
[0. 0. 0. ... 0. 0. 0.]

all included in that.
[0. 0. 0. ... 0. 0. 0.]

all included. absolutely, yes.
[0. 0. 0. ... 0. 0. 0.]

and your unit 2 program, you got it, you right on it. i mean 737, but increase in 787, we had a block extension in the quarter that was a big driver of that units, sorry, that program margin increase.
[0. 0. 0. ... 0. 0. 0.]

continued healthy sales activity contributed to 893 net new airplane orders during the year adding to our robust backlog stands at nearly 5,900 airplanes and is worth $412 billion. our backlog equates to about seven years production at current rates.b commercial airplane milestones in 2018 included the delivery of the 787 dreamliner and the first airplane fro

yes. just for clarity, 2020, production system will be operating in five months, when we look at that delivery rate, slightly increasing over the current 3.5 months delivery rate, that's the combination of 777 and 777x as greg mentioned.
[0. 0. 0. ... 0. 0. 0.]

next we will go to sheila kahyaoglu with jefferies. please go ahead.
[0. 0. 0. ... 0. 0. 0.]

going back to commercial profitability just because this is such a standout, how sustainable is the 100 bps of margin improvement? are there any mix impact we should be thinking about with the 777 coming in with this changing customers dynamics for any pricing dynamics that would alter that trajectory?
[0. 0. 0. ... 0. 0. 0.]

in particular, we see significant ongoing potential to apply our machine learning capabilities across our businesses. in our advertising business, machine learning has enabled innovation in advertisers ability to match consumer intent into bit more effectively for improved roi. it has also enhanced the ability of

so i think the increase performance of the permian is a good new story. we did spend little more capital last year because we were finding that we can drill more hole we have changed our basis of designs, so little bit of capital overrun was related to the good news story that we are getting a lot more production out of the permian. and our guidance has been we are free cash flow positive in 2020, and i think that抯 still a good way for you to think about it. as we have reached the crossover points it crosses over.
[0. 0. 0. ... 0. 0. 0.]

and we have increased the dividend that pat has already addressed the confidence in increasing the rate at which we are repurchasing shares and our intent to sustain that through the cycle. having strong free cash flow creates alternatives and we intend to use the free cash flow to be very mindful of the need for shareholder distributions and also to look for good investment opportunities. i mentioned we were able to meet all four priorities this last

divestments are driven by a view on strategic alignments with our broader portfolio and our view of the future, the resource potential that remains particular asset, will it compete for capital within our portfolio and there are good things as i mentioned earlier that cannot and then can we receive fair value. so that maybe a little bit of a function of what's the macro environment and the forward view on commodity price. but we are in a position that i think you can expect us to continue to high-grade our portfolio.
[0. 0. 0. ... 0. 0. 0.]

yes. so mike, maybe i should have asked it differently. so it seems like you guys are experiencing healthy enough appetite for assets if you were a seller. is that a good way to think about it?
[0. 0. 0. ... 0. 0. 0.]

yes, everything we are talking to people about right now we think we are likely to receive very good value.
[0. 0. 0. ... 0. 0. 0.]

our last question for today comes from the line of biraj borkhataria from rbc capital markets. your 

within this budget, the cash component is 13.7 billion while the remaining 6.3 billion is expenditures by affiliates, primarily tco and cpchem. in our 2019 budget, 3.6 billion is allocated to the permian and another 1.6 billion is allocated to other shale and tight assets. we expect approximately 70% of our total 2019 spends to deliver cash within two years. our current spend profile has significantly lower execution risk relative to the past, and we have several large scale major capital projects underway concurrently.
[0. 0. 0. ... 0. 0. 0.]

turning to slide 11. i would like to provide an update on our portfolio optimization efforts. during 2018, we received before tax asset sale proceeds of $2 billion, with the largest contributors being the divestment of our southern africa refining and marketing business and our interest in the elk hills field in california. we recently completed the sale of our interest in the rosebank project west of shetlands in the uk.
[0. 0. 0. ... 0. 0. 0.]

you see we've got really strong cash flows coming in right now, and the commitment to a competitive increase in the dividends the confidence to step up through right a share repurchases is evidence of our confidence that we've got those cash flows coming in, in a price environments, any reasonable price environment as pat has said, that we will be able to sustain those kinds of payouts.
[0. 0. 0. ... 0. 0. 0.]

the other thing i would just point out is, our capital spending is still the same. and we have got the ability to provide strong production growth, sustain the kind of cash margins that you have seen out of our portfolio and do that at really modest capital spending relative to our history.
[0. 0. 0. ... 0. 0. 0.]

the second question i guess would just be on that capital spending budget specifically for 2019. the permian piece pretty flattish year-over-year which i think you've highlighted last quarter. the non-permian shale piece just got the up quite a bit here. and i just wa

the third thing is, it provides good strong economics and because of our system in the three kind of strategic levers that i just talked about we ought to be able to optimize that refinery as a part of our system in a way that is different than what the current owner can simply because they don't have those other assets and those other positions.
[0. 0. 0. ... 0. 0. 0.]

and so within our business, this fills a bit of a gap, it gives us the ability to capture value in multiple different dimensions. and overtime, we will evaluate what investments we may choose to make there as we would in the other refinery. i would expect those to be relatively modest. i would expect them to be thoughtfully paced overtime and fit within the level of spending that we've established over the past many years in our downstream business.
[0. 0. 0. ... 0. 0. 0.]

lloyd walmsley
[0. 0. 0. ... 0. 0. 0.]

our next question comes from the line of neil mehta from goldman sachs. your question please.
[0. 0. 0. ...

the other thing when you抮e growing your business, it's important to pay attention to unit cost and we've seen unit cost come down significantly. we see this year another 2% reduction or so in unit cost, and as you look out to 2020 and 2021, i think that number can go up even more in terms of the percent reduction or the other way to say as unit cost can come down even more. so, we need to be prepared to be competitive in an environment where prices are not what we look to and we will continue to work on cost efficiencies across our entire portfolio.
[0. 0. 0. ... 0. 0. 0.]

just a very quick follow-up, can you talk about the ramp-up progress at big foot?
[0. 0. 0. ... 0. 0. 0.]

yes, so, we have got the first well online and it's been performing very well. it came on in november of last year. the second well is being drilled and completed as we speak, and we anticipate that going on here in the first quarter. so we will steadily move through the process of adding wells at bigfoot and y

our next question comes from the line of blake fernandez from simmons. your question please.
[0. 0. 0. ... 0. 0. 0.]

two questions for you. one: could you talk a little bit about venezuela? i know it's early days, but obviously you do have exposure there, both upstream and downstream and just any helpful thoughts that might help us out on our end.
[0. 0. 0. ... 0. 0. 0.]

yes, i can give you quick update on venezuela, blake. first and most important thing for us is the safety of our people on the ground, and so that's what we are really focused on. we also want to be sure the operations where we have an interest are safe and environmentally sound. and i can tell you that that is the case. we have worked closely with the governments to be sure that we understand the intent of the sanctions within a number of new general licenses issued by the treasury department. and so, we are in close consultation to be sure we understand them and how they are to be applied.
[0. 0. 0. ... 0. 0. 0.]



mark zuckerberg
[0. 0. 0. ... 0. 0. 0.]

and i'll add one thing, which i think david has said this a couple of times, but i think it's worth emphasizing that while i'm excited about the road map that we have and it's going to be great over the long term, the growth of the business over the next year, a few quarters or the near term is going to be mostly based on the growth of stories and the core news feed work. and stories is - we have a lot of work still to go there to make it - monetize at the same levels as news feed. and i'm confident that we're going to get there, but i want to make sure that we're giving the right outlook on how we expect the near future to go.
[0. 0. 0. ... 0. 0. 0.]

operator
[0. 0. 0. ... 0. 0. 0.]

your next question comes from the line of mark may from citi.
[0. 0. 0. ... 0. 0. 0.]

now however, this raises a broader set of values questions about how to use these systems. one question is about who decides what speech is acceptable and what isn't. right now,

all right. so for groups, the main thing that we're focused on is making it so that connecting with communities of people that you're interested in is going to be as central to the experience as connecting with friends and family. so it's not just a feature. it's going to become more of an organizing principle for more of the activity in the app. and friends and family is always going to be really central to what we do, but we just think that there's an opportunity now to do more and to make it so that people can also be a part of these meaningful communities. hundreds of millions of people already tell us that the groups that they're a part of on facebook or at least a few meaningful ones are the most important part of their social experience. there's a lot of data, sociological data outside, that shows that a physical group membership in the world off the internet has been declining for decades. so i think that building groups is - it obviously cannot replace people getting together 

and i think in the last six months or a year alone, there have been hundreds, if not thousands, of cases where we're we've been able to get first responders to people when they needed help because of this approach of being more proactive on looking at the content. the same goes for things around election interference and more proactively looking for inauthentic behavior. and we've taken down a lot of effort by different nation states to harm or interfere in elections that way. so we're just going to go down the list of every basic type of bad content. and we do report this publicly, going back to your question. we issue a transparency report. it's our content enforcement report. right now, we're doing it, i think it's every six months, but the goal is to get that to the cadence by, i think it's the end of this year, we're going to be doing it quarterly and doing calls to discuss the results just like we do for earnings because we think that this stuff is really important as well, at th

as always, thank you for being on this journey with us. and now, here is sheryl to talk about our business.
[0. 0. 0. ... 0. 0. 0.]

finally, on capital allocation. our primary use continues to be to support organic growth in our businesses, followed by retaining flexibility for acquisitions. after taking these needs into account, our board has authorized the repurchase of up to an additional 12.5 billion of our class c capital stock.
[0. 0. 0. ... 0. 0. 0.]

sheryl sandberg
[0. 0. 0. ... 0. 0. 0.]

thanks, mark, and hi, everyone. we had a strong fourth quarter and a good end to the year. q4 mobile ad revenue was $15.5 billion, increasing 36% year-over-year and contributing approximately 93% of our total ad revenue. full year mobile ad revenue grew 45% compared to 2017. 2018 was a challenging and important year for us. as mark said, we made significant investments in safety and security and strengthened our defenses against election interference. we gave people tools to better control 

turning now to the financials. all comparisons are on a year-over-year basis unless otherwise noted. q4 total revenue was $16.9 billion, up 30% or 33% on a constant currency basis. had foreign exchange rates remained constant with q4 '17, total revenue would have been approximately $348 million higher. q4 total ad revenue was $16.6 billion, up 30% or 33% on a constant currency basis. in terms of regional ad revenue growth, asia pacific was strongest at 34%, followed by north america at 31% and europe at 28%. rest of world ad revenue grew 24% and was impacted by ongoing currency weakness and macroeconomic challenges. in q4, the average price per ad decreased 2% and the number of ad impressions served on our services increased 34%. impression growth was primarily driven by ads on instagram, including both feed and stories as well as facebook mobile news feed. the year-over-year decline in average price per ad reflects an ongoing mix shift towards product services and geographies that mon

sheryl sandberg
[0. 0. 0. ... 0. 0. 0.]

i'll take the stories question. one of the challenges that marketers have is keeping up where consumers are. if you think about our history, people made the shift to mobile before marketers did, and i think one of the successes we've had is we made it easier for advertisers to move into a mobile environment. and just as we did that in mobile, now we're very focused on doing that in the new things that people are doing, and stories is a big part of that, messaging will be further out, but as important as well. so i think the fact that we've already gotten 2 million advertisers to move into stories is because we've gotten better at making it easier. we launched our automatic placements and expanded it, which converts feed ads into a format that works for stories and delivers the ads wherever they'll get the best results. so our goal is to make it as easy as possible for marketers to get to the format of stories and then deliver the ads where they'

david wehner
[0. 0. 0. ... 0. 0. 0.]

yes, i can start on the macro environment, eric. obviously, we delivered strong results in q4. as we look out into 2019 further, that's - the macro economy is certainly a potential headwind and risk to the business just given the sensitivity of the advertising business to a slowdown in growth. obviously, we believe we've got the best advertising products out there in terms of being able to deliver measurable business results to clients. and so we think that does help us in that environment, but clearly, macroeconomics stands out there as a risk on top of other issues that we face, leading to a deceleration of revenue growth in 2019.
[0. 0. 0. ... 0. 0. 0.]

mark zuckerberg
[0. 0. 0. ... 0. 0. 0.]

i'll talk about watch and video. so there, we've really had this dynamic over the last 12 to 18 months where we've limited the amount of video that we've shown in order to make sure - in news feed, to make sure that it doesn't displace interactions, socia

david wehner
[0. 0. 0. ... 0. 0. 0.]

justin, i can probably take both of those. in terms of our ability to continue to grow the advertising business, it's about working to develop the best products we can to enable advertisers to achieve their end business results. targeting is obviously very important in that. one of the things i would point out is that from a pricing perspective, there are headwinds that we might face on targeting, given the overall privacy landscape in 2019. and so i think that is another factor that presents risk in our ability to continue to grow arpu. so i would point that out as being an issue. as well, we're seeing a mix shift towards stories. and that is going to be something that will contribute to a deceleration of our revenue growth. so that's another factor that's leading to deceleration of revenue growth in 2019. in terms of your first question, justin, about the impact of the press cycle, i would just - i'd probably just let the numbers stand for themse

when you look at the chart we put in our earnings letter, which has the weekly growth rate, you can just see how steady it is. and we鈥檙e just continuing to work away on all the things that we鈥檝e always done. and what鈥檚 wonderful is the internet entertainment market is just growing, so we鈥檙e continuing to fulfill a need that we see.
[0. 0. 0. ... 0. 0. 0.]

and eric鈥
[0. 0. 0. ... 0. 0. 0.]

do you want add anything?
[0. 0. 0. ... 0. 0. 0.]

our effective tax rate was 11.2% for the fourth quarter, reflecting a discrete benefit due to the reversal of an accrual made as a result of updated guidance associated with the u.s tax act. net income was $8.9 billion and earnings per diluted share were $12.77.
[0. 0. 0. ... 0. 0. 0.]

from the lenovo smart clock that wakes you up in the morning to real-time navigation that helps during your commute. to a build in interpreter that translates conversations across dozens of languages on google home. and speaking of languages, over the past year the g

and eric, just to add on specifically to narrowly answer your question on content spend for 2019, we鈥檙e not giving individual expense item 鈥 expense line item guidance, but i will say that it was $7.5 billion in content amortization in 2018. and i think you can obviously expect that to grow and the trajectory should be pretty similar. but the other thing to bear in mind is that we鈥檝e also committed to growing the operating margin as well in 2019 by about 300 basis points year-over-year to 13%. so, those will work together, so you鈥檒l see improved margin, but also higher content spend as well.
[0. 0. 0. ... 0. 0. 0.]

and then we do see that payback eric, as greg mentioned earlier, an increased engagement, so which again continuing the virtuous cycle, where you鈥檝e got more 鈥 the more investment you鈥檙e putting in, the more people are finding content that they love and the more they have value in the service.
[0. 0. 0. ... 0. 0. 0.]

well, speaking to higher engagement, i think in reading 

 eric, there is one piece of data that didn鈥檛 make the release and that鈥檚 what percentage of people chose frosties versus sugar puffs. the answer is 73% for frosties. 
[0. 0. 0. ... 0. 0. 0.]

that鈥檚 a level of data transparency. we have not seen our content yet鈥
[0. 0. 0. ... 0. 0. 0.]

 it was critical data point of the quarter.
[0. 0. 0. ... 0. 0. 0.]

 completely anecdotal, but the sheridan house picked frosties multiple times. so we fed into those numbers, my wife and i. let鈥檚 bring it all together. now that we鈥檝e talked a little bit about a price increase subscriber trends, how money gets reinvested back into content. spence, i鈥檇 love to turn to you when say, when you think about the free cash flow profile of the business, some of the commentary in the letter around improving free cash flow from 2019 and beyond, how do you think about funding the business, the approach the business has always taken to the capital markets? any perspective you have that you think might be different

 sure. and i think some has been here for a decade plus. it鈥檚 sort of pulling that long thread of increasingly using partners in different ways to promote the service and to make it easier for members and members to be to sign up. so, we鈥檝e been doing partners for a long, long time. it鈥檚 sort of been this march from integration on devices and just makes that a point to engage with the service to doing things like billing, on behalf of or we do billing integration. and now the latest sort of iteration that we鈥檙e working with is, is bundling model, right. and so we鈥檙e early on in that process, but i would say we鈥檙e quite excited by the results that we鈥檙e seeing. and i think mostly, it鈥檚 because we believe it allows us to access a segment of consumers, who are big entertainment fans, but maybe, they鈥檙e not as sort of technology forward or early adopters.
[0. 0. 0. ... 0. 0. 0.]

 and so, they haven鈥檛 signed up with us directly. and so by putting netflix on a set-top box, which are using t

well, the one thing is our main goal is to make the best content. and we鈥檝e said 鈥 we鈥檝e said in previous quarters that that is a combination of several different business models depending on who owns the ip. so, what we鈥檙e going to do is make the best show and not be stuck on the business model, because the consumer really doesn鈥檛 understand that or we even want to spend any time thinking about it
[0. 0. 0. ... 0. 0. 0.]

so by way of example, last year, we had 140 different shows around the world that premiered on a network somewhere and on netflix everywhere else in the world. next year, it鈥檚 more to closer to 180. and these are combination of co-producing with local producers in other countries; it shows that then air on a network in that country and then premier on netflix. but when i say co-production, i mean, we come in at the script stage, we come in at the first money stage, we鈥檙e involved creatively with the production of that show
[0. 0. 0. ... 0. 0. 0.]

bodyguard is a good

thanks, keith, for the question. let me start and then, amy, you can add to this. first of all, it is very important for us to ensure that we did everything to enable linkedin to keep their product and cultural ethos of putting members first and innovating on their behalf. i mean, that was sort of our priority one, two and three. and that's what you see in their sessions growth, engagement growth, their quality member growth. and obviously that all translates into the revenue growth as well across all of the marketing solutions, talent solutions, and sales solutions.
[0. 0. 0. ... 0. 0. 0.]

we also, during that one year, done integrations. you see it. i see it every day in my outlook mobile. i see it in sales navigator and dynamics. and so, you will see us – with windows 10, so you'll see us continue to do these integrations that add value again to both the microsoft 365 and dynamics users, as well as linkedin members.
[0. 0. 0. ... 0. 0. 0.]

and clearly that's increasing engagemen

the layer above that is the place which we are very excited about. we've seen lots of consecutive quarters of growth in our higher-level services but we're now seeing some good scale. i, for the first time, talked about cosmos db. this was actually a database we just launched last year. i mean, i've been around databases for a long time. i've never seen a product that's gotten to this kind of scale this quickly.
[0. 0. 0. ... 0. 0. 0.]

and so we're very bullish about what can happen in the higher-level services and we'll continue to build on that piece. but as i said, one of the key things is, architecturally, the way we build azure, the way we build office 365, the way we build our gaming cloud and the way we build even dynamics are all pretty much one architecture.
[0. 0. 0. ... 0. 0. 0.]

and you see that even in the way customers use it. so overall to your specific question on azure, the growth will moderate as the numbers become big, and they've already become very big. but that 

the overall economy is certainly also quite good, and the installed base had actually gotten older. and so i think what you're starting to see is a process whereby there's a great product, there's a good macro environment. and you've got customers who really want to move to a modern infrastructure. a modern infrastructure has to both be secure at its very core, and that can result, as you're seeing through that confluence of events, in a very strong pc market with very strong pro performance. and certainly, the guide for q4 continues to imply all those factors.
[0. 0. 0. ... 0. 0. 0.]

weve added new facial recognition capabilities, which will attribute remarks to specific meeting attendees. and we are adding new cortana capability to make calls, join a meeting or initiate three-way calling just using your voice.
[0. 0. 0. ... 0. 0. 0.]

great. thanks very much.
[0. 0. 0. ... 0. 0. 0.]

thanks, brad. we'll take next question now, please.
[0. 0. 0. ... 0. 0. 0.]

thank you. our next que

but to your previous question, even there, there are multiple trends here, and amy referenced it in her remarks, which is for example, virtualization still continues to be a growth driver of server products. the other growth driver of server products is cybersecurity and the security value in our servers. so that's one.
[0. 0. 0. ... 0. 0. 0.]

the fact that we now have sql and, for example, when you think about sql itself, it's a hybrid product. you can tier sql databases with the cloud. sql is an ai product because we have the one database that actually allows you to write python and r in situ, store procedures right in your database.
[0. 0. 0. ... 0. 0. 0.]

so, for example, when we talk about data and ai close to data, because computation will always go wherever data is. and a lot of data shows up in relational databases and we have a growth driver there as well. and then there is the hybrid choices, where if somebody's building a smart factory, they're now looking and saying, what

relationship analytics for sales and marketing leverage the microsoft graph and data from social networks to improve customer relationships, and predictive lead scoring helps sellers identify and focus on high-quality leads.
[0. 0. 0. ... 0. 0. 0.]

good afternoon and thank you for joining us today. on the call with me are satya nadella, chief executive officer; amy hood, chief financial officer; frank brod, chief accounting officer; and carolyn frantz, deputy general counsel and corporate secretary.
[0. 0. 0. ... 0. 0. 0.]

were investing in our business applications platform capabilities across power bi, powerapps, flow and a common data model. now customers can extend dynamics 365 and office 365 and quickly build applications using data from across the organization as well as third-party data with minimal custom code.
[0. 0. 0. ... 0. 0. 0.]

the new power platform enables customers like inter cars, a leading european auto parts company, to go from paper to digitized workflows withi

second, cybersecurity. in response to escalating cyber attacks around the world, we are leading a bold initiative to defend and protect our customers. we recently led a coalition of 34 global technology and security companies in signing the cybersecurity tech accord. the accord is an important first step by the industry to help create a safer and more secure online environment for everyone.
[0. 0. 0. ... 0. 0. 0.]

finally, we recently established the ai and ethics in engineering and research committee at microsoft to ensure we always advance ai in an ethical and responsible way to benefit our customers and the broader society. this includes new investments in technology to detect and address bias in ai systems. microsoft stands for trust, and this will continue to be a differentiating focus for us moving forward.
[0. 0. 0. ... 0. 0. 0.]

with that, i'll hand it over to amy to cover our financial results in more detail and share our outlook. and i look forward to rejoining for your que

enterprise services revenue increased 8% and 5% in constant currency, with growth in premium support services and microsoft consulting services more than offsetting the continued decline in custom support agreements for windows server 2003.
[0. 0. 0. ... 0. 0. 0.]

segment gross margin dollars grew 16% and 14% in constant currency, and gross margin percentage declined with the growing mix of azure iaas and paas revenue mostly offset by another quarter of material improvement in azure gross margin.
[0. 0. 0. ... 0. 0. 0.]

operating expenses increased 9% and 7% in constant currency, driven by our continued investment in sales capacity and cloud engineering operating income increased 24% up investment in sales capacity and cloud engineering. operating income increased 24%, up 21% in constant currency.
[0. 0. 0. ... 0. 0. 0.]

now to the results of more personal computing. revenue from the segment was $9.9 billion, up 13% and 11% in constant currency, with significantly better than expect

in gaming, we expect a higher revenue growth rate than q3, as we continue to benefit from third-party game title performance and user engagement on our platform. we expect cogs between $9.6 billion and $9.8 billion, including 1 point of growth from fx. we expect operating expenses of $9.8 billion to $9.9 billion, with 1 point of growth from fx. this would place us slightly above the high end of our prior range for the full year operating expense growth due to the impact from fx and incremental revenue-driven expenses that support our continued strong top line growth.
[0. 0. 0. ... 0. 0. 0.]

thank you so much for taking the question. two, if i could. on youtube, you never have a number of brands in the marketplace between youtube premium, tv, youtube music. how are you thinking about positioning those brands against a global opportunity, especially in mobile to consume media on a global scale and how you鈥檙e positioning those brands for the opportunity. and then, ruth, i wanted to come 

now, if you think about some of the dynamics that we've been going through in the intelligent cloud segment, in particular the way i tend to think about that, as you've seen, we're now 20% growth this quarter in that server and product services kpi, 17% on a constant currency basis, and are sort of confident that you should continue to see that, as i said, into q4 and then into fy 2019 as well.
[0. 0. 0. ... 0. 0. 0.]

i tend to think about that as we'll have significant revenue growth in that segment. we'll have significant gross margin dollar growth in that segment, and you'll actually continue to see operating margin dollar growth that's significant in that segment even as we reinvest into it, given the top line signal.
[0. 0. 0. ... 0. 0. 0.]

if you think about gross margins in particular, what you'll see is azure continuing to be a growing percentage of the total revenue growth. so even with significant improvement again in, what satya was talking about, some of the lower level i

the other aspect of this, elon, which we've been doing extremely well, is capital efficiency. we have dramatically cut back on capital expense, and we are spending it in a very efficient manner. we talked about it in the letter on model 3 and gigafactory shanghai. we talked about it for model y. there are just so many learnings that we are incorporating, and we just want to beat what we did with model 3 and the kind of spending we had for the returns we got.
[0. 0. 0. ... 0. 0. 0.]

absolutely. i mean, we're confident that our capex per unit of production for shanghai factory and for model y will be less than half of what we did for model 3. internally, we think it might be a quarter but that's probably too good to believe, but it's definitely less than half.
[0. 0. 0. ... 0. 0. 0.]

our next question comes from david tamberrino with goldman sachs.
[0. 0. 0. ... 0. 0. 0.]

okay. and we expect that exponential to continue. so with the deliveries this year being - even in the face of - i

our next question comes from toni sacconaghi with bernstein.
[0. 0. 0. ... 0. 0. 0.]

you've talked repeatedly about the need to drive down costs, which, in turn, drives the elasticity of demand for cars. and i'm wondering if you can talk about how much of a price differential between the $50,000 model 3 and the $35,000 model 3 is structural, meaning that powertrain costs for evs are just structurally higher than they are for internal combustion engine cars. and where do you think that difference is today and when that is no longer a factor? so is - or maybe said another way, is the bigger driver in getting to lower costs and lower - and more affordability on the model 3, is it really around the powertrain and getting that at parity? or is it everything else about tesla not being as efficient as other manufacturers that is causing the higher price right now? and have i follow-up, please.
[0. 2. 0. ... 0. 0. 0.]

it's both, it's both, the vehicle and both the powertrain. so i split my t

yes, exactly. our leases are legit. the - it usually expects a small business. tax write-off is important for the - for leasing. so...
[0. 0. 0. ... 0. 0. 0.]

okay. and then i have just, like, two quick housekeeping questions. one, is there a restructuring charge that you expect in the first quarter? how much is it? and is it included in your expectation of a small profit?
[0. 0. 0. ... 0. 0. 0.]

yes, it is included in that. it's difficult to say exactly what that is. at this point, it's, let's say, roughly around $40 million, but that number can vary slightly.
[0. 0. 0. ... 0. 0. 0.]

okay. and then just the last one is...
[0. 0. 0. ... 0. 0. 0.]

sorry, go ahead.
[0. 0. 0. ... 0. 0. 0.]

yes, the last one is, this change in your service parts structure to make things more distributed rather than in the parts warehouse is, would that be like a meaningful working capital drag? what's the cash impact of that?
[0. 0. 0. ... 0. 0. 0.]

doug, on the first one, obviously we have thousands

again.
[0. 0. 0. ... 0. 0. 0.]

yes, from tesla.
[0. 0. 0. ... 0. 0. 0.]

yes.
[0. 0. 0. ... 0. 0. 0.]

deepak, i think it's now been - you first started with tesla about 11 years ago, right?
[0. 0. 0. ... 0. 0. 0.]

great. thank you. yes, i had a follow-up on to anthony's questions on cloud. it doesn鈥檛 seem like you want to share an update on the revenue run rate. but i was wondering if maybe you can share with us what you鈥檙e seeing in terms of year-over-year growth rate, and in particular are they growing faster than what the competitors disclosed in their public results? because maybe they will help think about the pace of growth in your cloud business. and then, secondarily i was just wondering if you can give us a sense of the types of workloads, if there's any commonality to the types of workloads, you might be running work frequently than not. thank you.
[0. 0. 0. ... 0. 0. 0.]

when - close to that, yes.
[0. 0. 0. ... 0. 0. 0.]

yes, almost 11 years. thank you for your tremendo

[indiscernible]call it and you have to tap the center screen to cancel it. so you can cancel it if you want. we just have to - it's like automatically going to happen. you just press cancel.
[0. 0. 0. ... 0. 0. 0.]

we're also improving parts distribution. so i think we made a strategic error in the past about not having service parts located at our service centers. we had them in parts distribution warehouses, which basically meant it was impossible to have a fast turnaround on servicing a car, because the car would come in, then the parts will be requested, they come to the service center, this would basically - even if they're very simple, repair could take days.
[0. 0. 0. ... 0. 0. 0.]

so we're going to be able to stock in all common parts at the service centers, so that it's possible to - - get your car serviced in 20 minutes or 15 minutes, even if it's a simple matter. i mean, it should be like eight minutes or whatever, eight minutes. it should be like lightning fast. but in or

then the next part of full self-driving will really be to - is traffic lights. it's hard. so stop streets are pretty easy because you can essentially geocode those and is recognized at all times.
[0. 0. 0. ... 0. 0. 0.]

traffic lights and intersections will be the next really tricky one. and then navigating complex parking lots and like - sort of like if you're underground in a mall parking lot with a lot of traffic and pedestrians and it's on multiple levels, that kind of thing is what gets tricky.
[0. 0. 0. ... 0. 0. 0.]

with the release of enhanced or advanced summon, you'll see the first indications of the car being able to navigate complex parking lots, and that's also coming up fairly soon, probably next month. and in development mode, the car does all the things that i just mentioned in development mode. it recognizes traffic lights and stop signs and basically has all the functionality in development mode. it's really just a question of getting your reliability of recognizing

sorry perhaps - if you're in the automotive industry you抣l understand how significant this is but maybe it's not as obvious to everyone is tesla has the first wholly owned manufacturing facility in china for any - of any automotive company. so this is profound, and we're very appreciative of the chinese government allowing us to do this. i think it is symbolic of [indiscernible] open the market. and if i - and you know, it [indiscernible], so like a note of appreciation for the chinese government in allowing us to do that. it's a very significant thing.
[0. 0. 0. ... 0. 0. 0.]

question i have is related to waymo and the autonomous driving opportunity. morgan stanley recently valued waymo at $175 billion. and my question is, what do they have that you don't have? and separately - so what do they have that you don't have?
[0. 0. 0. ... 0. 0. 0.]

and then separately, how important is the timing in the tesla story longer term? is this nice to have? is it really about evs and renewable en

yes. i mean, - there are multiple factors at play here. first of all, there's a lot of seasonality to automotive purchases. most people do not buy a new car in the middle of a blizzard. so january and february tends to be seasonally low and then picks up significantly around the early to mid-march time frame. in the u.s., we obviously have a pull forward of demand from the tax credit.
[0. 0. 0. ... 0. 0. 0.]

and yes, there's - so there's all those factors. but i feel very confident about model 3 demand. the customer happiness level with the car is incredible and i think probably the highest of any car in the world right now, i think. and so you can tell like, basically, nobody wants to sell their car.
[0. 0. 0. ... 0. 0. 0.]

we've basically almost doubled our fleet every year. every year, we make as many cars as we did in all prior years. so this is a very unusual thing to see for - especially for a large complex manufactured object, i think maybe the fastest that a complex manufactu

thanks, robbie. this is doug. i'll start with the ecommerce question, and brett can elaborate on it too if he would like to. we're not expecting the first quarter to go all the way to 40%. we think it'll start to ramp up from the fourth quarter to approximately 40% for the year. we're going to continue expanding our ecommerce business as it relates to food. online grocery's ramping up.
[0. 0. 0. ... 0. 0. 0.]

as we've said, we're going to almost double the number of locations that do online grocery. that will drive ecommerce growth to a certain level. and then on top of that, we've got the activity planned for both walmart.com and jet. so we've got an investment plan there.
[0. 0. 0. ... 0. 0. 0.]

we have an assortment plan and other innovations, as you saw last year, that will be occurring as we go through the year. so we think by the time we get to the end of the year and look back at the number for the total year, it will be approximately 40%.
[0. 0. 0. ... 0. 0. 0.]

yes. robbie,

so i think what you'll see is jet will go through a period of adjustment and then it'll start to grow again in the future but focused on specific markets and opportunities, whereas walmart will be the broad-based, big part of the business, and growing it will be a priority.
[0. 0. 0. ... 0. 0. 0.]

thank you.
[0. 0. 0. ... 0. 0. 0.]

rob, next question please?
[0. 0. 0. ... 0. 0. 0.]

and if i could just ask鈥
[0. 0. 0. ... 0. 0. 0.]

we鈥檙e limited to just one question, just to get through as many as we can, please. thanks.
[0. 0. 0. ... 0. 0. 0.]

thank you. your next question comes from oliver chen with cowen & company.
[0. 0. 0. ... 0. 0. 0.]

the key drivers were: first, content acquisition costs, primarily for youtube, mostly for our advertising supported content in what is a seasonally strong quarter for youtube, but also for our newer subscription businesses, youtube premium and youtube tv which have higher cac as a percentage of revenues. second, costs associated with our data c

so we're just going to calibrate this thing as we go through the year. it's one of our big levers, and we're excited about the fact that the investments we've made in the past are driving traffic and starting to get this productivity moving, which is ultimately what we're after.
[0. 0. 0. ... 0. 0. 0.]

and one of the metrics that i get excited about and have been for some time now because the team's doing such a good job is inventory. for us to be down in comp store inventory again for the 11th consecutive quarter while shelf in-stock is going up is awesome and remarkable.
[0. 0. 0. ... 0. 0. 0.]

by becoming stronger at mobile and leveraging digital capabilities, we improved in-store experiences, including our pharmacy and money services areas. we enabled easy reorder online. we're making the checkout experience easier with scan & go and also digitizing the returns process.
[0. 0. 0. ... 0. 0. 0.]

and the cash flow benefits and the other benefits are flowing through to the overall b

no, i don't think so. matt, my head, when you asked the question, started dividing it into food and non-food. there's nothing new on food. i think if you go back and listen to or watch our october analyst presentation where we walked through the strategy for food, all of that, even more convicted, still holds.
[0. 0. 0. ... 0. 0. 0.]

it's really all about providing more convenience for customers. customers that shop across all channels are important to us. as we said in october, u.s. customers that shop us in-store and online spend nearly twice as much as customers that only shop with us in stores. their loyalty to walmart strengthens overall.
[0. 0. 0. ... 0. 0. 0.]

on the non-food side, we're building a business. it's 鈥 non-food ecommerce is -- has not been our historic competency over the last few decades and the history of the company, and so we're learning something new.
[0. 0. 0. ... 0. 0. 0.]

we're trying to build an assortment that enables a margin ultimately, and that's got

and also, more specifically, for the current quarter, if you can just touch a little bit more detail regarding the transportation cost impact that you saw and what your expectations are on that particular line item going forward.
[0. 0. 0. ... 0. 0. 0.]

we're also becoming more efficient by changing the way we work, including leveraging technology to equip and empower our associates to be successful. they now have better information, tools and training.
[0. 0. 0. ... 0. 0. 0.]

sure. paul, appreciate it. i'll start with the operating income question. we're only giving guidance for this year coming forward. we did leverage expenses. excluding discrete items for the year, leverage got better as we went throughout the year. so i am optimistic about the expense leverage that we're seeing in the business, particularly in international and walmart u.s. stores, and i expect that we'll continue to see that progress.
[0. 0. 0. ... 0. 0. 0.]

so that gives us -- we've always talked about that b

the supercenter assortment is a big advantage, and we want to deliver low prices across the store, which also helps us drive traffic to the store and manage margins across the entire store. so evaluate the price investment through that lens rather than just grocery. and the returns we're seeing there are attractive. you can see it in the store traffic.
[0. 0. 0. ... 0. 0. 0.]

and we're going to continue our strategy as it relates to those. we're not cutting short the ecommerce investments. i think part of what we're doing now is just letting the business mature and learning how to become stronger operationally in ecommerce.
[0. 0. 0. ... 0. 0. 0.]

there may be a point this year and looking ahead where we want to be even more aggressive on ecommerce marketing, if we feel like those operational improvements are on the right path. we kind of watch that very continuously basically.
[0. 0. 0. ... 0. 0. 0.]

as it relates to grocery delivery, we've had this small pilot going on with our ow

the cost to acquire a new customer on a nationwide basis is cheaper with the walmart brand so we've been investing more in walmart.com on a national basis and reducing marketing investment in jet, except in certain urban markets.
[0. 0. 0. ... 0. 0. 0.]

thanks, rob. good morning, everyone, and thank you for joining us today to discuss walmart's fourth quarter and fiscal year 2018 results. joining us on today's call are walmart president and ceo, doug mcmillon; and cfo, brett biggs. doug and brett will have some opening remarks in a minute, and then we'll take your questions. we'll do our best to get to as many of you as possible.
[0. 0. 0. ... 0. 0. 0.]

due to this change, jet will not grow as quickly as it did in early days but it will be well positioned where we've chosen to focus the brand. we'll continue to evaluate ourselves on the total u.s. ecommerce growth number.
[0. 0. 0. ... 0. 0. 0.]

moving to sam's club. you'll remember that we made a decision to close 63 sam's club loc

let's move on to the quarter. we delivered a solid quarter to finish out the year as constant-currency revenue grew 3.1% to $135.1 billion. comp sales were positive in all 3 segments with growth of 2.6% and 2.4% at walmart u.s. and sam's club, respectively.
[0. 0. 0. ... 0. 0. 0.]

on a 2 year stack basis, comp sales accelerated for the third consecutive quarter for both of these segments at 4.4% and 4.8%, respectively. even more encouraging is that these results were driven by strong in-store traffic. international grew net sales 2.8% in constant currency, led by strength at walmex.
[0. 0. 0. ... 0. 0. 0.]

consolidated gross profit margin declined 61 basis points. approximately two thirds of the decline was driven by price investments in certain markets and the mix effect from our growing ecommerce business. the remaining one third was driven by sam's club inventory markdowns associated with closures and other international items, including the wind down of our brazil first-party eco

we recently announced some additional investments related to increased wages, training and benefits for our associates in the u.s. in addition to that, we'll look to accelerate investments in our customers through lower prices, and we'll make investments in technology, supply chain and ecommerce to better position the company for the future. we'll also continue to prioritize winning with customers in our grocery and fresh business, ensuring we make shopping with us simple and at a great value.
[0. 0. 0. ... 0. 0. 0.]

at the october meeting, doug talked about some decisions we had in the q, but it was too early to comment further at that time. during the quarter we took several actions, including: a wind down of the first-party ecommerce business in brazil, the closure of 63 sam's clubs locations in the u.s. and the decision to remove tobacco from certain locations at sam's. these decisions impact the guidance we gave in october, particularly in regards to total sales growth, so i'll q

can you just tell us if the entirety of that change is tax reform spending? or is any part of it reflective of higher cost in the business in some form or another?
[0. 0. 0. ... 0. 0. 0.]

yes, simeon. i still remain -- feel good about the cost management in the business, and we're making progress there. when we've given guidance back in october, we've talked about an operating income range that would be similar to where we had kind of been.
[0. 0. 0. ... 0. 0. 0.]

our guidance also assumes, among other things, that we don't conclude any additional business acquisitions, investments, restructurings or legal settlements. it's not possible to accurately predict demand for our goods and services, and therefore, our actual results could differ materially from our guidance.
[0. 0. 0. ... 0. 0. 0.]

so as we step back and we looked at everything, we've decided to make these investments that we talked about, and that's all included in the guidance that's there today.
[0. 0. 0. ... 0. 0. 0.]


your execution is really differentiated. we have a very, very strong client franchise business, but's it's in a business where there's been fundamental change and wallet change. i would highlight that if you go back and look at our wallet market shares before the financial crisis in 2005, '06 and '07, our wallet shares were in the 8%, 8.5% range. and if you look at our wallet shares today, our wallet shares are around 12%. and so there was an aberration during the 2009 kind of period where the wallet shares peaked, but we've continued to build this franchise, and we're laser focused on building it. the one thing that i said in my comments that i just want to reiterate is we accept the size of the wallet share that exists, and it's our job to run the business well based on that wallet share to allocate capital over time efficiently and to run that business in an effective way from a cost perspective, and we continue to do that while continuing to invest in the client franchise. and so s

# Build vocabulary and generate vectors

In [17]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(cleaned_text)
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np
import pandas as pd
import re


In [19]:
cvec = CountVectorizer(stop_words='english', min_df=3, max_df=0.5, ngram_range=(1,2))
sf = cvec.fit_transform(cleaned_text)

In [20]:
transformer = TfidfTransformer()
transformed_weights = transformer.fit_transform(sf)
weights = np.asarray(transformed_weights.mean(axis=0)).ravel().tolist()
weights_df = pd.DataFrame({'term': cvec.get_feature_names(), 'weight': weights})

weights_df.sort_values(by='weight', ascending=False).head(50)

term    weight
2813        question  0.029149
3881            year  0.025890
3519           think  0.024688
2482        operator  0.021028
1923            just  0.019740
1618          growth  0.018487
2794         quarter  0.016841
527         business  0.016509
2064            line  0.015677
3487           thank  0.015598
3496          thanks  0.014794
3921             yes  0.014156
450          billion  0.014090
2048            like  0.013450
708            comes  0.013228
2087              ll  0.013130
1544           going  0.013053
3713              ve  0.012960
2815  question comes  0.012876
815         continue  0.011508
2877          really  0.011302
2387             new  0.010897
3020         revenue  0.010696
3566            time  0.010485
709       comes line  0.010063
1294          expect  0.009807
1557            good  0.009587
936            david  0.009109
916        customers  0.008859
926             data  0.008743
598             cash  0.008669
2190          margin  0.008580
251            ahead  0.008574
60              2019  0.008558
1583           great  0.008541
2231           maybe  0.008465
2573          people  0.008464
3332         stephen  0.008307
3362          strong  0.008227
2134             lot  0.008173
3914           years  0.008065
3779            want  0.008058
2164            make  0.007976
3005         results  0.007896
3038           right  0.007879
2847            rate  0.007819
54              2018  0.007767
3106          scherr  0.007755
3333  stephen scherr  0.007755
2118            look  0.007751